language: rust
sudo: false
rust:
- nightly
- beta
- stable
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- cargo build
- cargo test
- if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo bench --verbose; fi
- cargo doc
after_success:
- travis-cargo --only stable doc-upload
- |
  if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
    wget https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz &&
    tar xzf v33.tar.gz && mkdir kcov-33/build && cd kcov-33/build &&
    cmake -DCMAKE_INSTALL_PREFIX=~/.local .. && make &&
    make install &&
    cd ../.. &&
    ~/.local/bin/kcov --verify \
        --coveralls-id=$TRAVIS_JOB_ID \
        --exclude-pattern=/.cargo \
        target/kcov target/debug/usi-*
  fi
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: SDn9Nr1HbyNtmotnbzEG+SFQyseKlxHLVPWsZtCGBy9dfLGYwmOS4GlnvHZvXLly51EnENGNUc/g5/hW15F0urG0PtcE0n/8RSYQ7czAyq1CSzZgjAsHe52e4ENSl0qWUHi/xPuaYVQy1v/O88SyUGMPqmkBWppN87na3qhwcClUUSUtpQzkVz19W+zx55cdWL5agycmYDlb7FZ8rogRqaFP+2XEOrV8RLsjUyp9D4MZU/kcHtzIj4v94Wrz+JTF52fcRbd/ecIQAknZxM1t0HGn6v8aWcz14Y1uDfamkVnKvSvc3EGc60le3SvoFmdRKaHEWH7Ir9ansgjC8jjjvH461tYUDdvMCuY3HwWfVtZxRQoOV4QkWaHT2edYX+Uh77DRRg1tmfjlZdTdcNdjBhCenepJNGjExgJSapwJCo5H4Hjrpi9RSVsOqmDjFTsXHWsc8rVsQNb24rz/1l92xO4U12ChTxT5uWye92nejmgSfXwzR7yipJM+DYsEaq+I2bl5AzDCdruFaFC9ITYxoeYxQZFwLctq4bivxme6J1qIXIpG19TYTnoTFWeoK60QxHHs9ShkY7LbRSmW/QY0DRqCjYHiAiGp5Ty6jIfmZO1vLvEQ1MJAtTBFP8N6SeEtvo70/bRaNrIM5hfOTKr8cEILqSmEHwDASTM++O5YVJY=
